spring:
  datasource:
    url: jdbc:mysql://192.168.5.122:3306/shanghu
    username: toowell
    password: toowell2013db
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
